export const CAR_DATA = [
  {
    name: "BMW M3",
    price: "60",
    img: "/images/cars-lg/bmw.png",
    model: "M3",
    brand: "BMW",
    year: "2019",
    doors: "4",
    air: "Yes",
    transmission: "Manual",
    fuel: "Gasoline",
  },
  {
    name: "Ford Bronco",
    price: "35",
    img: "/images/cars-lg/bronco.webp",
    model: "Bronco",
    brand: "Ford",
    year: "2021",
    doors: "4",
    air: "Yes",
    transmission: "Auto",
    fuel: "Gasoline",
  },
  {
    name: "Tesla Model 3",
    price: "15",
    img: "/images/cars-lg/tesla.webp",
    model: "Model 3",
    brand: "Tesla",
    year: "2022",
    doors: "4",
    air: "Yes",
    transmission: "Auto",
    fuel: "Electric",
  },
  {
    name: "Mercedes S-class",
    price: "45",
    img: "/images/cars-lg/mercedes.png",
    model: "S-class",
    brand: "Mercedes",
    year: "2022",
    doors: "4",
    air: "Yes",
    transmission: "Auto",
    fuel: "Gasoline",
  },
  {
    name: "Jaguar F-Type",
    price: "55",
    img: "/images/cars-lg/jaguar.png",
    model: "F-Type",
    brand: "Jaguar",
    year: "2015",
    doors: "2",
    air: "Yes",
    transmission: "Manual",
    fuel: "Gasoline",
  },
];
