import Banner from "@/components/Banner";
import CarFleet from "@/components/CarFleet";
import FAQ from "@/components/FAQ";
import Footer from "@/components/Footer";
import Modal from "@/components/Modal";
import Navbar from "@/components/Navbar";
import Reviews from "@/components/Reviews";
import Booking from "components/Booking";
import Hero from "components/Hero";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  const bookRef = useRef(null);

  const scrollToBook = () =>
    bookRef.current.scrollIntoView({ behavior: "smooth", block: "center" });

  // Modal display

  const [DisplayModal, setDisplayModal] = useState(false);

  // Modal data

  const [BookingData, setBookingData] = useState({
    carmodel: "",
    pickup: "",
    dropoff: "",
    start: "",
    end: "",
  });

  // Disabling scroll when modal is open

  useEffect(() => {
    if (DisplayModal === true) {
      document.body.style.overflow = "hidden";
      document.body.style.paddingRight = "15px";
    } else {
      document.body.style.overflow = "auto";
      document.body.style.paddingRight = "0px";
    }
  }, [DisplayModal]);

  return (
    <>
      <Head>
        <title>Rental App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <Navbar />
      <Hero scrollToBook={scrollToBook} />
      <Booking
        bookRef={bookRef}
        setDisplayModal={setDisplayModal}
        setBookingData={setBookingData}
      />
      <Modal
        BookingData={BookingData}
        DisplayModal={DisplayModal}
        setDisplayModal={setDisplayModal}
      />
      <Reviews />
      <CarFleet scrollToBook={scrollToBook} />
      <Banner />
      <FAQ />
      <Footer />
    </>
  );
}
